import type { AdminAccessContext } from './types';

export type NowAdminGroup =
  | 'orders'
  | 'catalog'
  | 'marketing'
  | 'geography'
  | 'payments'
  | 'services'
  | 'compliance'
  | 'notifications'
  | 'system';

export type NowAdminPermission = keyof AdminAccessContext['permissions'];
export type NowAdminMutationMode = 'crud' | 'update-only' | 'workflow' | 'readonly';

export type NowTableDefinition = {
  table: string;
  labelAr: string;
  descriptionAr: string;
  group: NowAdminGroup;
  permission: NowAdminPermission;
  mutationMode: NowAdminMutationMode;
  primaryKey: string[];
  titleColumns: string[];
  searchColumn?: string;
  orderBy: string;
  orderAscending?: boolean;
  requiredColumns?: string[];
  protectedColumns?: string[];
};

export const NOW_ADMIN_GROUPS: Record<
  NowAdminGroup,
  { labelAr: string; descriptionAr: string }
> = {
  orders: {
    labelAr: 'الطلبات والتشغيل',
    descriptionAr: 'الطلبات، عناصرها، سجل الحالات والتقييمات.',
  },
  catalog: {
    labelAr: 'المتاجر والكتالوج',
    descriptionAr: 'المتاجر، الأقسام، المنتجات، المتغيرات، الصور ومناطق الخدمة.',
  },
  marketing: {
    labelAr: 'التسويق والعروض',
    descriptionAr: 'البانرات، محتواها، ربط المنتجات والمناطق، وكوبونات الخصم.',
  },
  geography: {
    labelAr: 'المدن ومناطق الخدمة',
    descriptionAr: 'المدن، حدود التغطية ورسوم وتقديرات التوصيل الافتراضية.',
  },
  payments: {
    labelAr: 'الدفع والمالية',
    descriptionAr: 'طرق الدفع، الحسابات، الرسوم وإثباتات الدفع.',
  },
  services: {
    labelAr: 'الخدمات والحجوزات',
    descriptionAr: 'باقات الخدمات، الحجوزات وإثباتات دفعها.',
  },
  compliance: {
    labelAr: 'المراجعات والامتثال',
    descriptionAr: 'الروشتات، التحقق العمري وطلبات حذف الحساب.',
  },
  notifications: {
    labelAr: 'الإشعارات',
    descriptionAr: 'اشتراكات Push، الـOutbox والتذاكر الناتجة من Expo.',
  },
  system: {
    labelAr: 'النظام والإدارة',
    descriptionAr: 'إعدادات التطبيق، أعضاء الإدارة، الأخطاء وسجل ترحيل الوسائط.',
  },
};

export const NOW_TABLES: NowTableDefinition[] = [
  {
    table: 'orders',
    labelAr: 'الطلبات',
    descriptionAr: 'السجل الرئيسي لكل طلب في Navienty Now.',
    group: 'orders',
    permission: 'view_orders',
    mutationMode: 'workflow',
    primaryKey: ['id'],
    titleColumns: ['order_code', 'customer_name', 'store_name_ar_snapshot'],
    searchColumn: 'order_code',
    orderBy: 'created_at',
  },
  {
    table: 'order_items',
    labelAr: 'عناصر الطلبات',
    descriptionAr: 'Snapshot المنتجات والكميات والأسعار داخل كل طلب.',
    group: 'orders',
    permission: 'view_orders',
    mutationMode: 'readonly',
    primaryKey: ['id'],
    titleColumns: ['product_name_ar_snapshot', 'order_id'],
    searchColumn: 'product_name_ar_snapshot',
    orderBy: 'created_at',
  },
  {
    table: 'order_status_history',
    labelAr: 'سجل حالات الطلب',
    descriptionAr: 'سجل غير قابل للتحرير لكل انتقال في حالة الطلب.',
    group: 'orders',
    permission: 'view_orders',
    mutationMode: 'readonly',
    primaryKey: ['id'],
    titleColumns: ['new_status', 'order_id', 'actor_reference'],
    searchColumn: 'new_status',
    orderBy: 'created_at',
  },
  {
    table: 'order_ratings',
    labelAr: 'تقييمات الطلبات',
    descriptionAr: 'تقييمات العملاء المرتبطة بالطلبات والمتاجر.',
    group: 'orders',
    permission: 'view_orders',
    mutationMode: 'readonly',
    primaryKey: ['id'],
    titleColumns: ['rating', 'order_id', 'store_id'],
    orderBy: 'created_at',
  },
  {
    table: 'store_categories',
    labelAr: 'فئات المتاجر',
    descriptionAr: 'Restaurant / Supermarket / Pharmacy / Bookstore وغيرها.',
    group: 'catalog',
    permission: 'manage_catalog',
    mutationMode: 'crud',
    primaryKey: ['id'],
    titleColumns: ['name_ar', 'slug'],
    searchColumn: 'name_ar',
    orderBy: 'sort_order',
    orderAscending: true,
    requiredColumns: ['slug', 'name_ar', 'name_en'],
  },
  {
    table: 'stores',
    labelAr: 'المتاجر',
    descriptionAr: 'بيانات المتجر، الموقع، الإغلاق اليدوي والتقييم.',
    group: 'catalog',
    permission: 'manage_catalog',
    mutationMode: 'crud',
    primaryKey: ['id'],
    titleColumns: ['name_ar', 'slug', 'phone'],
    searchColumn: 'name_ar',
    orderBy: 'sort_order',
    orderAscending: true,
    requiredColumns: ['category_id', 'city_id', 'slug', 'name_ar'],
    protectedColumns: ['rating_avg', 'rating_count'],
  },
  {
    table: 'store_business_hours',
    labelAr: 'مواعيد المتاجر',
    descriptionAr: 'مواعيد الفتح والإغلاق لكل يوم في الأسبوع.',
    group: 'catalog',
    permission: 'manage_catalog',
    mutationMode: 'crud',
    primaryKey: ['id'],
    titleColumns: ['store_id', 'day_of_week', 'is_open'],
    orderBy: 'day_of_week',
    orderAscending: true,
    requiredColumns: ['store_id', 'day_of_week'],
  },
  {
    table: 'store_service_areas',
    labelAr: 'تغطية المتاجر',
    descriptionAr: 'ربط المتاجر بمناطق الخدمة ورسوم وحدود الطلب لكل متجر.',
    group: 'catalog',
    permission: 'manage_catalog',
    mutationMode: 'crud',
    primaryKey: ['id'],
    titleColumns: ['store_id', 'service_area_id', 'delivery_fee'],
    orderBy: 'created_at',
    requiredColumns: ['store_id', 'service_area_id'],
  },
  {
    table: 'catalog_categories',
    labelAr: 'أقسام الكتالوج',
    descriptionAr: 'الأقسام والأقسام الفرعية داخل كل متجر.',
    group: 'catalog',
    permission: 'manage_catalog',
    mutationMode: 'crud',
    primaryKey: ['id'],
    titleColumns: ['name_ar', 'slug', 'store_id'],
    searchColumn: 'name_ar',
    orderBy: 'sort_order',
    orderAscending: true,
    requiredColumns: ['store_id', 'slug', 'name_ar'],
  },
  {
    table: 'products',
    labelAr: 'المنتجات',
    descriptionAr: 'كل المنتجات والأسعار والتوفر وقيود الروشتة والعمر.',
    group: 'catalog',
    permission: 'manage_catalog',
    mutationMode: 'crud',
    primaryKey: ['id'],
    titleColumns: ['name_ar', 'slug', 'sku'],
    searchColumn: 'name_ar',
    orderBy: 'sort_order',
    orderAscending: true,
    requiredColumns: [
      'store_id',
      'catalog_category_id',
      'product_type',
      'slug',
      'name_ar',
      'base_price',
    ],
  },
  {
    table: 'product_variants',
    labelAr: 'متغيرات المنتجات',
    descriptionAr: 'الأحجام والاختيارات والأسعار وSKU لكل Product Variant.',
    group: 'catalog',
    permission: 'manage_catalog',
    mutationMode: 'crud',
    primaryKey: ['id'],
    titleColumns: ['name_ar', 'slug', 'sku'],
    searchColumn: 'name_ar',
    orderBy: 'sort_order',
    orderAscending: true,
    requiredColumns: ['product_id', 'slug', 'name_ar', 'price'],
  },
  {
    table: 'product_images',
    labelAr: 'صور المنتجات',
    descriptionAr: 'كل صور المنتجات، صورة الغلاف والترتيب.',
    group: 'catalog',
    permission: 'manage_catalog',
    mutationMode: 'crud',
    primaryKey: ['id'],
    titleColumns: ['product_id', 'image_url'],
    orderBy: 'sort_order',
    orderAscending: true,
    requiredColumns: ['product_id', 'image_url'],
  },
  {
    table: 'home_banners',
    labelAr: 'البانرات',
    descriptionAr: 'بانرات Home، الجدولة، الجمهور، الـCTA والمحتوى والثيم.',
    group: 'marketing',
    permission: 'manage_catalog',
    mutationMode: 'crud',
    primaryKey: ['id'],
    titleColumns: ['admin_label', 'placement', 'action_type'],
    searchColumn: 'admin_label',
    orderBy: 'sort_order',
    orderAscending: true,
    requiredColumns: ['admin_label', 'image_url'],
  },
  {
    table: 'home_banner_images',
    labelAr: 'صور البانرات',
    descriptionAr: 'الصور الإضافية المرتبطة بكل Banner.',
    group: 'marketing',
    permission: 'manage_catalog',
    mutationMode: 'crud',
    primaryKey: ['id'],
    titleColumns: ['banner_id', 'image_url'],
    orderBy: 'sort_order',
    orderAscending: true,
    requiredColumns: ['banner_id', 'image_url'],
  },
  {
    table: 'home_banner_products',
    labelAr: 'منتجات البانرات',
    descriptionAr: 'المنتجات المعروضة داخل Banner من نوع Detail Screen.',
    group: 'marketing',
    permission: 'manage_catalog',
    mutationMode: 'crud',
    primaryKey: ['id'],
    titleColumns: ['banner_id', 'product_id'],
    orderBy: 'sort_order',
    orderAscending: true,
    requiredColumns: ['banner_id', 'product_id'],
  },
  {
    table: 'home_banner_service_areas',
    labelAr: 'مناطق ظهور البانرات',
    descriptionAr: 'تحديد مناطق الخدمة التي يظهر فيها كل Banner.',
    group: 'marketing',
    permission: 'manage_catalog',
    mutationMode: 'crud',
    primaryKey: ['id'],
    titleColumns: ['banner_id', 'service_area_id'],
    orderBy: 'created_at',
    requiredColumns: ['banner_id', 'service_area_id'],
  },
  {
    table: 'vouchers',
    labelAr: 'الكوبونات',
    descriptionAr: 'أكواد الخصم، النطاق، حدود الاستخدام والمدة.',
    group: 'marketing',
    permission: 'manage_catalog',
    mutationMode: 'crud',
    primaryKey: ['id'],
    titleColumns: ['code', 'title_ar', 'discount_type'],
    searchColumn: 'code',
    orderBy: 'created_at',
    requiredColumns: ['code', 'discount_type', 'discount_value'],
  },
  {
    table: 'voucher_categories',
    labelAr: 'فئات الكوبونات',
    descriptionAr: 'جدول الربط بين الكوبونات وفئات المتاجر.',
    group: 'marketing',
    permission: 'manage_catalog',
    mutationMode: 'crud',
    primaryKey: ['voucher_id', 'category_id'],
    titleColumns: ['voucher_id', 'category_id'],
    orderBy: 'created_at',
    requiredColumns: ['voucher_id', 'category_id'],
  },
  {
    table: 'voucher_redemptions',
    labelAr: 'استخدامات الكوبونات',
    descriptionAr: 'السجل المالي/التشغيلي لحجز وصرف وإلغاء الكوبونات.',
    group: 'marketing',
    permission: 'view_orders',
    mutationMode: 'readonly',
    primaryKey: ['id'],
    titleColumns: ['voucher_id', 'order_id', 'status'],
    orderBy: 'created_at',
  },
  {
    table: 'cities',
    labelAr: 'المدن',
    descriptionAr: 'المدن التي يعمل فيها Navienty Now.',
    group: 'geography',
    permission: 'manage_settings',
    mutationMode: 'crud',
    primaryKey: ['id'],
    titleColumns: ['name_ar', 'name_en', 'slug'],
    searchColumn: 'name_ar',
    orderBy: 'sort_order',
    orderAscending: true,
    requiredColumns: ['slug', 'name_ar', 'name_en'],
  },
  {
    table: 'service_areas',
    labelAr: 'مناطق الخدمة',
    descriptionAr: 'التغطية الجغرافية، Polygon، الرسوم والحد الأدنى الافتراضي.',
    group: 'geography',
    permission: 'manage_settings',
    mutationMode: 'crud',
    primaryKey: ['id'],
    titleColumns: ['name_ar', 'code', 'city_id'],
    searchColumn: 'name_ar',
    orderBy: 'sort_order',
    orderAscending: true,
    requiredColumns: ['city_id', 'code', 'name_ar', 'name_en'],
  },
  {
    table: 'payment_methods',
    labelAr: 'طرق الدفع',
    descriptionAr: 'طرق الدفع، الرسوم، تعليمات التحويل وسياسة إثبات الدفع.',
    group: 'payments',
    permission: 'manage_finance',
    mutationMode: 'crud',
    primaryKey: ['id'],
    titleColumns: ['name_ar', 'code', 'processing_fee_type'],
    searchColumn: 'name_ar',
    orderBy: 'sort_order',
    orderAscending: true,
    requiredColumns: ['code', 'name_ar', 'name_en'],
  },
  {
    table: 'payment_method_accounts',
    labelAr: 'حسابات التحصيل',
    descriptionAr: 'الأرقام/الحسابات/IBAN وQR المرتبطة بكل طريقة دفع.',
    group: 'payments',
    permission: 'manage_finance',
    mutationMode: 'crud',
    primaryKey: ['id'],
    titleColumns: ['label', 'account_name', 'account_number'],
    searchColumn: 'label',
    orderBy: 'priority',
    orderAscending: true,
    requiredColumns: ['payment_method_id'],
  },
  {
    table: 'order_payment_proofs',
    labelAr: 'إثباتات دفع الطلبات',
    descriptionAr: 'صور التحويل وحالة مراجعتها للطلبات.',
    group: 'payments',
    permission: 'manage_orders',
    mutationMode: 'workflow',
    primaryKey: ['id'],
    titleColumns: ['order_id', 'status', 'amount_snapshot'],
    orderBy: 'created_at',
  },
  {
    table: 'service_booking_payment_proofs',
    labelAr: 'إثباتات دفع الخدمات',
    descriptionAr: 'إثباتات الدفع المرتبطة بحجوزات الخدمات.',
    group: 'payments',
    permission: 'manage_orders',
    mutationMode: 'workflow',
    primaryKey: ['id'],
    titleColumns: ['service_booking_id', 'status', 'amount_snapshot'],
    orderBy: 'created_at',
  },
  {
    table: 'service_packages',
    labelAr: 'باقات الخدمات',
    descriptionAr: 'الخدمات القابلة للحجز، السعر، الصورة والـmetadata.',
    group: 'services',
    permission: 'manage_catalog',
    mutationMode: 'crud',
    primaryKey: ['id'],
    titleColumns: ['name_ar', 'slug', 'price'],
    searchColumn: 'name_ar',
    orderBy: 'sort_order',
    orderAscending: true,
    requiredColumns: ['slug', 'name_ar', 'price'],
  },
  {
    table: 'service_bookings',
    labelAr: 'حجوزات الخدمات',
    descriptionAr: 'كل حجوزات الخدمات وحالتها وبيانات العميل.',
    group: 'services',
    permission: 'view_orders',
    mutationMode: 'workflow',
    primaryKey: ['id'],
    titleColumns: ['booking_code', 'package_name_ar', 'customer_name'],
    searchColumn: 'booking_code',
    orderBy: 'created_at',
  },
  {
    table: 'prescription_submissions',
    labelAr: 'الروشتات',
    descriptionAr: 'الروشتات المرفوعة وربطها بالطلبات وقرارات المراجعة.',
    group: 'compliance',
    permission: 'manage_orders',
    mutationMode: 'workflow',
    primaryKey: ['id'],
    titleColumns: ['order_id', 'store_id', 'status'],
    orderBy: 'created_at',
  },
  {
    table: 'account_deletion_requests',
    labelAr: 'طلبات حذف الحساب',
    descriptionAr: 'طلبات الخصوصية، الـpreflight، خطة scrub وحالة التنفيذ.',
    group: 'compliance',
    permission: 'manage_settings',
    mutationMode: 'workflow',
    primaryKey: ['id'],
    titleColumns: ['user_id', 'status', 'source'],
    orderBy: 'requested_at',
  },
  {
    table: 'customer_push_subscriptions',
    labelAr: 'اشتراكات Push',
    descriptionAr: 'Expo tokens، المنصة، إصدار التطبيق وآخر ظهور.',
    group: 'notifications',
    permission: 'manage_settings',
    mutationMode: 'readonly',
    primaryKey: ['id'],
    titleColumns: ['platform', 'user_id', 'app_version'],
    orderBy: 'created_at',
  },
  {
    table: 'customer_notification_outbox',
    labelAr: 'Notification Outbox',
    descriptionAr: 'طابور الإشعارات وحالة المحاولات والأخطاء.',
    group: 'notifications',
    permission: 'manage_settings',
    mutationMode: 'readonly',
    primaryKey: ['id'],
    titleColumns: ['event_key', 'status', 'resource_type'],
    searchColumn: 'event_key',
    orderBy: 'created_at',
  },
  {
    table: 'customer_notification_tickets',
    labelAr: 'Expo Notification Tickets',
    descriptionAr: 'Tickets الناتجة من Expo وحالة التحقق من كل إرسال.',
    group: 'notifications',
    permission: 'manage_settings',
    mutationMode: 'readonly',
    primaryKey: ['id'],
    titleColumns: ['expo_ticket_id', 'status', 'error_code'],
    searchColumn: 'expo_ticket_id',
    orderBy: 'created_at',
  },
  {
    table: 'app_settings',
    labelAr: 'إعدادات التطبيق',
    descriptionAr: 'الإعدادات المركزية: التشغيل، الصيانة، العملة، الدعم والـgates.',
    group: 'system',
    permission: 'manage_settings',
    mutationMode: 'update-only',
    primaryKey: ['singleton'],
    titleColumns: ['app_name', 'app_slug', 'timezone'],
    searchColumn: 'app_name',
    orderBy: 'singleton',
    orderAscending: true,
  },
  {
    table: 'admin_members',
    labelAr: 'أعضاء إدارة Now',
    descriptionAr: 'صلاحيات أعضاء فريق Navienty Now داخل لوحة الإدارة.',
    group: 'system',
    permission: 'manage_settings',
    mutationMode: 'crud',
    primaryKey: ['user_id'],
    titleColumns: ['role', 'user_id', 'is_active'],
    searchColumn: 'role',
    orderBy: 'created_at',
    requiredColumns: ['user_id'],
    protectedColumns: ['created_by'],
  },
  {
    table: 'mobile_client_error_events',
    labelAr: 'أخطاء تطبيق الموبايل',
    descriptionAr: 'الأخطاء المرسلة من تطبيق Navienty Now للتشخيص.',
    group: 'system',
    permission: 'manage_settings',
    mutationMode: 'readonly',
    primaryKey: ['id'],
    titleColumns: ['error_name', 'platform', 'app_version'],
    searchColumn: 'error_name',
    orderBy: 'created_at',
  },
  {
    table: 'media_migration_log',
    labelAr: 'سجل ترحيل الوسائط',
    descriptionAr: 'Audit log لترحيل روابط الصور والملفات إلى Storage.',
    group: 'system',
    permission: 'manage_settings',
    mutationMode: 'readonly',
    primaryKey: ['id'],
    titleColumns: ['entity_table', 'entity_id', 'field_path'],
    searchColumn: 'entity_table',
    orderBy: 'migrated_at',
  },
];

const TABLE_MAP = new Map(NOW_TABLES.map((definition) => [definition.table, definition]));

export function getNowTableDefinition(table: string) {
  return TABLE_MAP.get(table) ?? null;
}

export function getNowTablesForGroup(group: NowAdminGroup) {
  return NOW_TABLES.filter((definition) => definition.group === group);
}

export function canAccessNowTable(
  access: AdminAccessContext,
  definition: NowTableDefinition,
) {
  return Boolean(access.permissions[definition.permission]);
}

export function canMutateNowTable(
  access: AdminAccessContext,
  definition: NowTableDefinition,
) {
  return (
    canAccessNowTable(access, definition) &&
    (definition.mutationMode === 'crud' || definition.mutationMode === 'update-only')
  );
}
